export const siteUrl = "https://www.noktatransfer.com.tr";

export const districtPages = [
  { name: "Konak", slug: "konak-transfer", zone: "Merkez", note: "Saat Kulesi, Alsancak, Kordon", route: "Konak - Adnan Menderes Havalimanı" },
  { name: "Balçova", slug: "balcova-transfer", zone: "Merkez", note: "Teleferik, İnciraltı, AVM hattı", route: "Balçova - Adnan Menderes Havalimanı" },
  { name: "Bayraklı", slug: "bayrakli-transfer", zone: "Merkez", note: "Adliye, plazalar ve sahil hattı", route: "Bayraklı - Alsancak" },
  { name: "Bornova", slug: "bornova-transfer", zone: "Merkez", note: "Ege Üniversitesi, Forum Bornova, merkez", route: "Bornova - Adnan Menderes Havalimanı" },
  { name: "Buca", slug: "buca-transfer", zone: "Merkez", note: "Şirinyer, Kozağaç, üniversite çevresi", route: "Buca - Adnan Menderes Havalimanı" },
  { name: "Çiğli", slug: "cigli-transfer", zone: "Kuzey", note: "OSB, Mavişehir ve kuzey çevre yolu", route: "Çiğli - Karşıyaka" },
  { name: "Gaziemir", slug: "gaziemir-transfer", zone: "Merkez", note: "Adnan Menderes Havalimanı, fuar ve çevre yolu", route: "Gaziemir - Adnan Menderes Havalimanı" },
  { name: "Güzelbahçe", slug: "guzelbahce-transfer", zone: "Sahil", note: "Sahil yolu, marina ve Urla bağlantısı", route: "Güzelbahçe - Urla" },
  { name: "Karabağlar", slug: "karabaglar-transfer", zone: "Merkez", note: "Bozyaka, Yeşilyurt ve şehir merkezi", route: "Karabağlar - Konak" },
  { name: "Karşıyaka", slug: "karsiyaka-transfer", zone: "Merkez", note: "Bostanlı, Mavişehir ve sahil hattı", route: "Karşıyaka - Bornova" },
  { name: "Narlıdere", slug: "narlidere-transfer", zone: "Sahil", note: "Sahil, oteller ve Balçova bağlantısı", route: "Narlıdere - Adnan Menderes Havalimanı" },
  { name: "Aliağa", slug: "aliaga-transfer", zone: "Kuzey", note: "Liman, rafineri ve sanayi hattı", route: "Aliağa - İzmir Merkez" },
  { name: "Bergama", slug: "bergama-transfer", zone: "Kuzey", note: "Tarihi merkez ve kuzey aksı", route: "Bergama - Adnan Menderes Havalimanı" },
  { name: "Çeşme", slug: "cesme-transfer", zone: "Sahil", note: "Alaçatı, marina ve otel bölgeleri", route: "Çeşme - Adnan Menderes Havalimanı" },
  { name: "Dikili", slug: "dikili-transfer", zone: "Sahil", note: "Sahil, liman ve yazlık bölgeler", route: "Dikili - İzmir Merkez" },
  { name: "Foça", slug: "foca-transfer", zone: "Sahil", note: "Eski Foça, Yeni Foça ve sahil rotası", route: "Foça - Adnan Menderes Havalimanı" },
  { name: "Karaburun", slug: "karaburun-transfer", zone: "Sahil", note: "Yarımada, sahil ve yazlık hatları", route: "Karaburun - İzmir Merkez" },
  { name: "Kınık", slug: "kinik-transfer", zone: "Kuzey", note: "Kuzey ilçe ve Bergama bağlantısı", route: "Kınık - İzmir Merkez" },
  { name: "Menemen", slug: "menemen-transfer", zone: "Kuzey", note: "Ulukent, şehir merkezi ve çevre yolu", route: "Menemen - Karşıyaka" },
  { name: "Seferihisar", slug: "seferihisar-transfer", zone: "Sahil", note: "Sığacık, marina ve sahil rotaları", route: "Seferihisar - Adnan Menderes Havalimanı" },
  { name: "Urla", slug: "urla-transfer", zone: "Sahil", note: "İskele, bağ yolu ve sahil hattı", route: "Urla - İzmir Merkez" },
  { name: "Bayındır", slug: "bayindir-transfer", zone: "Güney", note: "İç ilçe, terminal ve merkez rotası", route: "Bayındır - İzmir Merkez" },
  { name: "Beydağ", slug: "beydag-transfer", zone: "Güney", note: "Ödemiş hattı ve güney aksı", route: "Beydağ - Adnan Menderes Havalimanı" },
  { name: "Kemalpaşa", slug: "kemalpasa-transfer", zone: "Güney", note: "Sanayi, OSB ve şehir dışı bağlantı", route: "Kemalpaşa - Bornova" },
  { name: "Kiraz", slug: "kiraz-transfer", zone: "Güney", note: "Güney ilçe ve Ödemiş bağlantısı", route: "Kiraz - İzmir Merkez" },
  { name: "Menderes", slug: "menderes-transfer", zone: "Güney", note: "Havalimanı, Gümüldür ve sahil bağlantısı", route: "Menderes - Adnan Menderes Havalimanı" },
  { name: "Ödemiş", slug: "odemis-transfer", zone: "Güney", note: "Birgi, merkez ve güney rotası", route: "Ödemiş - Adnan Menderes Havalimanı" },
  { name: "Selçuk", slug: "selcuk-transfer", zone: "Güney", note: "Efes, Şirince ve otel bağlantıları", route: "Selçuk - Adnan Menderes Havalimanı" },
  { name: "Tire", slug: "tire-transfer", zone: "Güney", note: "İç ilçe, terminal ve merkez hattı", route: "Tire - İzmir Merkez" },
  { name: "Torbalı", slug: "torbali-transfer", zone: "Güney", note: "Pancar, Ayrancılar ve sanayi hattı", route: "Torbalı - Adnan Menderes Havalimanı" },
  { name: "Mordoğan", slug: "mordogan-transfer", zone: "Sahil", note: "Karaburun yolu, yazlık ve koylar", route: "Mordoğan - Adnan Menderes Havalimanı" },
  { name: "Ürkmez", slug: "urkmez-transfer", zone: "Sahil", note: "Seferihisar hattı, sahil ve yazlıklar", route: "Ürkmez - İzmir Merkez" },
  { name: "Gümüldür", slug: "gumuldur-transfer", zone: "Sahil", note: "Menderes sahili ve yazlık bölgeler", route: "Gümüldür - Adnan Menderes Havalimanı" }
];
